### ISSUE TITLE
MOMZA-212 Send translated welcome SMS

### ISSUE THREAD

**Issue by imsickofmaps** [praekeltfoundation/ndoh-jsbox#46]
The lazytext thing was screwing up fixtures

**Comment by imsickofmaps** [comment]
from Justin: It seems like the `create_outbound_message()` util there is using the toolkit's http api tools. Those don't do any handling of translation (iirc the only parts of the sandbox that will do translation are states and `self.im.outbound`). You can get the user's current translator (the function that takes in lazy text and returns translated text) with `self.im.user.i18n`, and then apply that to the lazy text before giving it to the `http.post()`. So something like `self.im.user.i18n($('foo'))` (it may make more sense for `create_outbound_message` to be calling the translator, but whichever makes more sense to you).

**Comment by gsvr** [comment]
Duplicate issue - handled in #38
