### ISSUE TITLE
PMTCT Optout to Vumi Fails

### ISSUE THREAD

**Issue by imsickofmaps** [praekeltfoundation/ndoh-jsbox#57]
```
2016-09-07T10:06:28+0000 [-] 
    HttpResponseError:
        reason: Could not parse response:
            SyntaxError: Unexpected token <
        response:
            code: 411
            request:
                method: PUT
                url: https://go.vumi.org/api/v1/go/optouts/msisdn/+27845091190
            body: <html>
            <head><title>411 Length Required</title></head>
            <body bgcolor="white">
            <center><h1>411 Length Required</h1></center>
            <hr><center>nginx/1.1.19</center>
            </body>
            </html>
```

**Comment by gsvr** [comment]
This works when making the request with Postman, possibly a URL encoding problem with the `+`?

**Comment by gsvr** [comment]
@smn I'm not sure who to ask for help on Praekelt's side on this. I'm trying to do a Vumi optout Put request, it works in Postman but fails when the code runs it. I'm thinking this is because Postman url-encodes the `+`.  Link to where I use it in the code: https://github.com/praekeltfoundation/ndoh-jsbox/blob/develop/src/ussd_pmtct.js#L289

**Comment by smn** [comment]
try urlencoding the msisdn like postman does?

**Comment by gsvr** [comment]
yeah, was hoping not to use a trial and error approach, but I can do that.

**Comment by smn** [comment]
Try adding `Content-Length: 0` as a header.

**Comment by smn** [comment]
Judging by http://stackoverflow.com/questions/18352190/why-i-get-411-length-required-error

**Comment by smn** [comment]
The log entry for yours shows `"PUT /api/v1/go/optouts/msisdn/+27727372369 HTTP/1.1" 411 181 "-" "-"` so it's encoding it fine. I suspect it's the missing Content-Length header.

**Comment by gsvr** [comment]
This only applies to the hybrid vumi / seed solution and can be closed if implementation is not needed before full switch to seed-stack.

**Comment by gsvr** [comment]
Closing this as project has switched to full seed-stack.
